types = {
    'INT': 'int',
    'FLOAT': 'float',
    'CHAR': 'char',
    'BOOL': 'bool',
}

operations = {
    '+': 0, 
    '-': 1, 
    '*': 2, 
    '/': 3, 
    '&&': 4, 
    '||': 5, 
    '==': 6, 
    '!=': 7, 
    '>': 8,
    '<': 9,
    '>=': 10, 
    '<=': 11,
    '=': 12,
}

class SemanticCube():
    

    semantic_cube = {
        'int': {
            'int': {
                '+': types['INT'],
                '-': types['INT'],
                '*': types['INT'],
                '/': types['INT'],
                '&&': types['BOOL'],
                '||': types['BOOL'],
                '==': types['BOOL'],
                '!=': types['BOOL'],
                '>': types['BOOL'],
                '<': types['BOOL'],
                '>=': types['BOOL'],
                '<=': types['BOOL'],
                '=': types['INT'],
            },
            'float': {
                '+': types['FLOAT'],
                '-': types['FLOAT'],
                '*': types['FLOAT'],
                '/': types['FLOAT'],
                '&&': 'ERROR',
                '||': 'ERROR',
                '==': 'ERROR',
                '!=': 'ERROR',
                '>': types['BOOL'],
                '<': types['BOOL'],
                '>=': types['BOOL'],
                '<=': types['BOOL'],
                '=': 'ERROR',
            },
            'char': {
                '+': types['CHAR'],
                '-': types['CHAR'],
                '*': 'ERROR',
                '/': 'ERROR',
                '&&': 'ERROR',
                '||': 'ERROR',
                '==': 'ERROR',
                '!=': 'ERROR',
                '>': 'ERROR',
                '<': 'ERROR',
                '>=': 'ERROR',
                '<=': 'ERROR',
                '=': 'ERROR',
            },
            'bool': {
                '+': 'ERROR',
                '-': 'ERROR',
                '*': 'ERROR',
                '/': 'ERROR',
                '&&': 'ERROR',
                '||': 'ERROR',
                '==': 'ERROR',
                '!=': 'ERROR',
                '>': 'ERROR',
                '<': 'ERROR',
                '>=': 'ERROR',
                '<=': 'ERROR',
                '=': 'ERROR',
            }
        },
        'float': {
            'int': {
                '+': types['FLOAT'],
                '-': types['FLOAT'],
                '*': types['FLOAT'],
                '/': types['FLOAT'],
                '&&': 'ERROR',
                '||': 'ERROR',
                '==': 'ERROR',
                '!=': 'ERROR',
                '>': types['BOOL'],
                '<': types['BOOL'],
                '>=': types['BOOL'],
                '<=': types['BOOL'],
                '=': 'ERROR',
            },
            'float': {
                '+': types['FLOAT'],
                '-': types['FLOAT'],
                '*': types['FLOAT'],
                '/': types['FLOAT'],
                '&&': 'ERROR',
                '||': 'ERROR',
                '==': types['BOOL'],
                '!=': types['BOOL'],
                '>': types['BOOL'],
                '<': types['BOOL'],
                '>=': types['BOOL'],
                '<=': types['BOOL'],
                '=': types['FLOAT']
            },
            'char': {
                '+': 'ERROR',
                '-': 'ERROR',
                '*': 'ERROR',
                '/': 'ERROR',
                '&&': 'ERROR',
                '||': 'ERROR',
                '==': 'ERROR',
                '!=': 'ERROR',
                '>': 'ERROR',
                '<': 'ERROR',
                '>=': 'ERROR',
                '<=': 'ERROR',
                '=': 'ERROR',
            },
            'bool': {
                '+': 'ERROR',
                '-': 'ERROR',
                '*': 'ERROR',
                '/': 'ERROR',
                '&&': 'ERROR',
                '||': 'ERROR',
                '==': 'ERROR',
                '!=': 'ERROR',
                '>': 'ERROR',
                '<': 'ERROR',
                '>=': 'ERROR',
                '<=': 'ERROR',
                '=': 'ERROR',
            }
        },
        'char': {
            'int': {
                '+': types['CHAR'],
                '-': types['CHAR'],
                '*': 'ERROR',
                '/': 'ERROR',
                '&&': 'ERROR',
                '||': 'ERROR',
                '==': 'ERROR',
                '!=': 'ERROR',
                '>': 'ERROR',
                '<': 'ERROR',
                '>=': 'ERROR',
                '<=': 'ERROR',
                '=': 'ERROR',
            },
            'float': {
                '+': 'ERROR',
                '-': 'ERROR',
                '*': 'ERROR',
                '/': 'ERROR',
                '&&': 'ERROR',
                '||': 'ERROR',
                '==': 'ERROR',
                '!=': 'ERROR',
                '>': 'ERROR',
                '<': 'ERROR',
                '>=': 'ERROR',
                '<=': 'ERROR',
                '=': 'ERROR',
            },
            'char': {
                '+': types['CHAR'],
                '-': types['CHAR'],
                '*': 'ERROR',
                '/': 'ERROR',
                '&&': 'ERROR',
                '||': 'ERROR',
                '==': types['BOOL'],
                '!=': types['BOOL'],
                '>': types['BOOL'],
                '<': types['BOOL'],
                '>=': types['BOOL'],
                '<=': types['BOOL'],
                '=': types['CHAR'],
            },
            'bool': {
                '+': 'ERROR',
                '-': 'ERROR',
                '*': 'ERROR',
                '/': 'ERROR',
                '&&': 'ERROR',
                '||': 'ERROR',
                '==': 'ERROR',
                '!=': 'ERROR',
                '>': 'ERROR',
                '<': 'ERROR',
                '>=': 'ERROR',
                '<=': 'ERROR',
                '=': 'ERROR',
            }
        },
        'bool': {
            'int': {
                '+': 'ERROR',
                '-': 'ERROR',
                '*': 'ERROR',
                '/': 'ERROR',
                '&&': 'ERROR',
                '||': 'ERROR',
                '==': 'ERROR',
                '!=': 'ERROR',
                '>': 'ERROR',
                '<': 'ERROR',
                '>=': 'ERROR',
                '<=': 'ERROR',
                '=': 'ERROR',
            },
            'float': {
                '+': 'ERROR',
                '-': 'ERROR',
                '*': 'ERROR',
                '/': 'ERROR',
                '&&': 'ERROR',
                '||': 'ERROR',
                '==': 'ERROR',
                '!=': 'ERROR',
                '>': 'ERROR',
                '<': 'ERROR',
                '>=': 'ERROR',
                '<=': 'ERROR',
                '=': 'ERROR',
            },
            'char': {
                '+': 'ERROR',
                '-': 'ERROR',
                '*': 'ERROR',
                '/': 'ERROR',
                '&&': 'ERROR',
                '||': 'ERROR',
                '==': 'ERROR',
                '!=': 'ERROR',
                '>': 'ERROR',
                '<': 'ERROR',
                '>=': 'ERROR',
                '<=': 'ERROR',
                '=': 'ERROR',
            },
            'bool': {
                '+': 'ERROR',
                '-': 'ERROR',
                '*': 'ERROR',
                '/': 'ERROR',
                '&&': types['BOOL'],
                '||': types['BOOL'],
                '==': types['BOOL'],
                '!=': types['BOOL'],
                '>': 'ERROR',
                '<': 'ERROR',
                '>=': 'ERROR',
                '<=': 'ERROR',
                '=': types['BOOL'],
            }
        }
    }
   
    def match_types(self, type1: str, type2: str, operator: str) -> str:
        if type1 not in types or type2 not in types:
            raise Exception('Unknown type used')
        
        if operator not in operations:
            raise Exception('Unknown operator used')
            
        sem_type1 = types[type1]
        sem_type2 = types[type2]
        result = self.semantic_cube[sem_type1][sem_type2][operator]
        return result